export const PAGE_LOGIN = 'LOGIN'
export const PAGE_HOME = 'HOME'
export const PAGE_SPAM = 'SPAM'
export const PAGE_FORUMS = 'FORUMS'
export const PAGE_UPDATES = 'UPDATES'
export const PAGE_SOCIAL = 'SOCIAL'